# Estructuras de datos en `pandas`: `DataFrame`s

Hemos visto que una serie en `pandas` es representa una colección de valores indexados por sendas etiquetas. 
La extensión natural (?) de una serie es una colección con múltiples valores arreglados en columnas indexados por una misma colección de etiquetas. Es decir, una tabla...
La estructura que representa tablas en `pandas` se llama _DataFrame_. Un `DataFrame` tiene un índice de filas (como las series) y un índice de columnas. 

> Se puede pensar un `DataFrame` como un diccionario de series que comparten un mismo índice.

Como las series, es habitual construir un `DataFrame` a partir de un diccionario. Veamos el siguiente diccionario para comenzar a trabajar. Como siempre, importamos los módulos indispensables:

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Titulo": [
        "The Philosopher's Stone",
        "The Chamber of Secrets",
        "The Prisoner of Azkaban",
        "The Goblet of Fire",
        "The Order of the Phoenix",
        "The Half-Blood Prince",
        "The Deathly Hallows"
    ],
    "Año de edición": [1997, 1998, 1999, 2000, 2003, 2005, 2007],
    "Páginas": [223, 251, 317, 636, 766, 607, 607],
}

df = pd.DataFrame(data)
df

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

El diccionario de origen asigna a cada clave una lista de elementos. Hemos generado un `DataFrame` a partir de un diccionario: los índices de filas se generan automáticamente, mientras que los índices (o etiquetas) de las columnas corresponden a las claves de cada una de las listas del diccionario.

> Si las listas que componen el diccionario de origen no son iguales, `pd.DataFrame` dará un error `ValueError: All arrays must be of the same length`.

Una conveniencia interesante en Jupyter Notebooks es que se puede imprimir la tabla en forma elegante:

In [3]:
print(df) 
display(df)
df # también funciona

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

Eventualmente uno podría querer ver sólo algunas filas:

In [76]:
display(df.head()) # muestra las primeras 5 filas
display(df.tail()) # muestra las últimas 5 filas

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766

                     Titulo  Año de edición  Páginas
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

El `DataFrame` usa la variable `index` como en las series, y la variable `columns` para describir las etiquetas de las columnas. Por ejemplo:

In [4]:
df2 = pd.DataFrame(data, index = ["a", "b", "c", "d", "e", "f", "g"], columns = ["Titulo", "Páginas", "Año de edición"])
df2

                     Titulo  Páginas  Año de edición
a   The Philosopher's Stone      223            1997
b    The Chamber of Secrets      251            1998
c   The Prisoner of Azkaban      317            1999
d        The Goblet of Fire      636            2000
e  The Order of the Phoenix      766            2003
f     The Half-Blood Prince      607            2005
g       The Deathly Hallows      607            2007

Notar que el orden de la lista de etiquetas que se pasa a `columns` se mantiene al crear el `DataFrame`. La lista que se usa en la creación de un `DataFrame` usando `columns` debe contener exactamente los mismos valores que las claves del diccionario, sino generará una columna con datos faltantes.

Para acceder a las etiquetas de filas y columnas, usamos los métodos `.index` y `.columns`.

In [5]:
print(f"Indices de filas: {df2.index}")
print(f"Indices de columnas: {df2.columns}")

Indices de filas: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
Indices de columnas: Index(['Titulo', 'Páginas', 'Año de edición'], dtype='str')

### Accediendo a los valores

Para acceder a las columnas podemos usar:

In [6]:
print(f"Valores de las filas: {df2.values}")
print(f"Valores de las columnas: {type(df2.values)}")

Valores de las filas: [["The Philosopher's Stone" 223 1997]
 ['The Chamber of Secrets' 251 1998]
 ['The Prisoner of Azkaban' 317 1999]
 ['The Goblet of Fire' 636 2000]
 ['The Order of the Phoenix' 766 2003]
 ['The Half-Blood Prince' 607 2005]
 ['The Deathly Hallows' 607 2007]]
Valores de las columnas: <class 'numpy.ndarray'>

El resultado de esta operación nos devuelve un arreglo 2D de NumPy, cuyo tipo de dato será el mínimo que pueda contener los tipos de datos de las columnas que lo componen. Por ejemplo, si nuestras columnas tienen datos en `float32` y `float64`, el tipo del arreglo de NumPy resultante será `float64`. En el caso anterior, los tipos de datos de las columnas son:

In [7]:
df2.dtypes

Titulo              str
Páginas           int64
Año de edición    int64
dtype: object

Es decir que los datos en `int64` de las columnas `Páginas` y `Año de edición` se promueven a `object`. 

El acceso a ciertas columnas en particular se hace como en los diccionarios:

In [10]:
print(f"La columna 'Titulo':\n {df2['Titulo']}")
print('---')
print(f"Tipo de la columna 'Titulo': {type(df2['Titulo'])}")
print('---')
print(f"Valores de la columna 'Titulo': {df2['Titulo'].values}")
print('---')
print(f"Tipo de la columna 'Titulo' .values: {type(df2['Titulo'].values)}")

La columna 'Titulo':
 a     The Philosopher's Stone
b      The Chamber of Secrets
c     The Prisoner of Azkaban
d          The Goblet of Fire
e    The Order of the Phoenix
f       The Half-Blood Prince
g         The Deathly Hallows
Name: Titulo, dtype: str
---
Tipo de la columna 'Titulo': <class 'pandas.Series'>
---
Valores de la columna 'Titulo': <ArrowStringArray>
[ 'The Philosopher's Stone',   'The Chamber of Secrets',
  'The Prisoner of Azkaban',       'The Goblet of Fire',
 'The Order of the Phoenix',    'The Half-Blood Prince',
      'The Deathly Hallows']
Length: 7, dtype: str
---
Tipo de la columna 'Titulo' .values: <class 'pandas.arrays.ArrowStringArray'>

Vemos que una columna en un `DataFrame` de `pandas` es representada efectivamente por una serie, de este modo, sus valores (obtenidos mediante `.values`) serán un arreglo de NumPy, como vimos antes. 

En el caso en que la etiqueta de una columna no contenga espacios, se puede acceder a la misma con el operador `.`:

In [82]:
df2.Titulo # es lo mismo que df2['Titulo']

a     The Philosopher's Stone
b      The Chamber of Secrets
c     The Prisoner of Azkaban
d          The Goblet of Fire
e    The Order of the Phoenix
f       The Half-Blood Prince
g         The Deathly Hallows
Name: Titulo, dtype: object

> Si uno quisiera usar esta propiedad en forma exhaustiva para todas las columnas, debería reemplazar las etiquetas de las mismas por nombres de variables válidos en Python

In [11]:
df2.columns = ["titulo", "paginas", "primer_edicion"]
df2

                     titulo  paginas  primer_edicion
a   The Philosopher's Stone      223            1997
b    The Chamber of Secrets      251            1998
c   The Prisoner of Azkaban      317            1999
d        The Goblet of Fire      636            2000
e  The Order of the Phoenix      766            2003
f     The Half-Blood Prince      607            2005
g       The Deathly Hallows      607            2007

In [12]:
df2.primer_edicion

a    1997
b    1998
c    1999
d    2000
e    2003
f    2005
g    2007
Name: primer_edicion, dtype: int64

> En el caso en que uno cree un `DataFrame` desde una base de datos, una buena práctica es mantener la consistencia entre las etiquetas de las columnas del `DataFrame` y las de la base de datos.

Se puede acceder a una determinada fila usando las etiquetas través de `.loc` o con índices enteros con `.iloc`:

In [14]:
df2

                     titulo  paginas  primer_edicion
a   The Philosopher's Stone      223            1997
b    The Chamber of Secrets      251            1998
c   The Prisoner of Azkaban      317            1999
d        The Goblet of Fire      636            2000
e  The Order of the Phoenix      766            2003
f     The Half-Blood Prince      607            2005
g       The Deathly Hallows      607            2007

In [13]:
print(f"Primer libro:\n{df2.iloc[0]}")
print(f"Segundo libro:\n{df2.loc['b']}")
print(f"Último libro:\n{df2.iloc[-1]}")

Primer libro:
titulo            The Philosopher's Stone
paginas                               223
primer_edicion                       1997
Name: a, dtype: object
Segundo libro:
titulo            The Chamber of Secrets
paginas                              251
primer_edicion                      1998
Name: b, dtype: object
Último libro:
titulo            The Deathly Hallows
paginas                           607
primer_edicion                   2007
Name: g, dtype: object

Y se puede acceder a un elemento particular de la tabla:

In [86]:
print(f"Título primer libro: {df2.iloc[0].titulo}")
print(f"Año de edición del segundo libro: {df2.loc['b', 'primer_edicion']}")
print(f"Año de edición del último libro: {df2.iloc[-1, 2]}")

Título primer libro: The Philosopher's Stone
Año de edición del segundo libro: 1998
Año de edición del último libro: 2007

La figura presenta los distintos tipos de acceso a los datos de un `DataFrame`

![](figuras/loc.png)

> Si se quisiera acceder a ciertas regiones de la tabla, se pueden reemplazar los valores individuales por rangos, tal como uno haría con NumPy

In [15]:
df2.loc[['a','d'],["titulo", "paginas"]]

                    titulo  paginas
a  The Philosopher's Stone      223
d       The Goblet of Fire      636

In [16]:
df2.loc[:'d',["titulo", "primer_edicion"]]

                    titulo  primer_edicion
a  The Philosopher's Stone            1997
b   The Chamber of Secrets            1998
c  The Prisoner of Azkaban            1999
d       The Goblet of Fire            2000

In [89]:
df2.iloc[0:3, :2]

                    titulo  paginas
a  The Philosopher's Stone      223
b   The Chamber of Secrets      251
c  The Prisoner of Azkaban      317

También se puede acceder a una parte de la tabla a partir de la aplicación de una condición. Veamos por ejemplo qué libros salieron en el siglo XXI. Para eso vemos qué elementos tienen valor de `primera_edicion` mayor a 2000:

In [90]:
df2['primer_edicion'] > 2000

a    False
b    False
c    False
d    False
e     True
f     True
g     True
Name: primer_edicion, dtype: bool

In [17]:
df2[df2['primer_edicion'] > 2000]

                     titulo  paginas  primer_edicion
e  The Order of the Phoenix      766            2003
f     The Half-Blood Prince      607            2005
g       The Deathly Hallows      607            2007

In [18]:
print(type(df2[df2['primer_edicion'] > 2000]))

<class 'pandas.DataFrame'>

### Modificando valores

Retomemos nuestro `DataFrame` inicial y agreguémosle una columna con la calificación promedio de cada libro dada por los lectores:

In [19]:
df = pd.DataFrame(data)
display(df)

                     Titulo  Año de edición  Páginas
0   The Philosopher's Stone            1997      223
1    The Chamber of Secrets            1998      251
2   The Prisoner of Azkaban            1999      317
3        The Goblet of Fire            2000      636
4  The Order of the Phoenix            2003      766
5     The Half-Blood Prince            2005      607
6       The Deathly Hallows            2007      607

In [20]:
df['Calificación'] = [4.5, 4.3, 4.6, 4.8, 4.7, 4.9, 4.9]
df

                     Titulo  Año de edición  Páginas  Calificación
0   The Philosopher's Stone            1997      223           4.5
1    The Chamber of Secrets            1998      251           4.3
2   The Prisoner of Azkaban            1999      317           4.6
3        The Goblet of Fire            2000      636           4.8
4  The Order of the Phoenix            2003      766           4.7
5     The Half-Blood Prince            2005      607           4.9
6       The Deathly Hallows            2007      607           4.9

Supongamos que queremos agregar una columna `Siglo` con el siglo en que fue escrito cada libro. Empecemos creando una columna:

In [21]:
df['Siglo'] = ""
df

                     Titulo  Año de edición  Páginas  Calificación Siglo
0   The Philosopher's Stone            1997      223           4.5
1    The Chamber of Secrets            1998      251           4.3
2   The Prisoner of Azkaban            1999      317           4.6
3        The Goblet of Fire            2000      636           4.8
4  The Order of the Phoenix            2003      766           4.7
5     The Half-Blood Prince            2005      607           4.9
6       The Deathly Hallows            2007      607           4.9

Esto crea la columna `Siglo` que no existe en la tabla, y le asigna el valor `""` a todas las filas. Podríamos haber completado la columna con una lista _con la misma cantidad de filas que la tabla_, pero mejor vamos a seleccionar aquellos libros del siglo XX, y completaremos los correspondientes valores en la nueva columna. Lo mismo haremos con los del siglo XXI:

In [23]:
df.loc[df['Año de edición'] <= 2000, 'Siglo'] = 'XX'
df.loc[df['Año de edición'] > 2000, 'Siglo'] = 'XXI'
df

                     Titulo  Año de edición  Páginas  Calificación Siglo
0   The Philosopher's Stone            1997      223           4.5    XX
1    The Chamber of Secrets            1998      251           4.3    XX
2   The Prisoner of Azkaban            1999      317           4.6    XX
3        The Goblet of Fire            2000      636           4.8    XX
4  The Order of the Phoenix            2003      766           4.7   XXI
5     The Half-Blood Prince            2005      607           4.9   XXI
6       The Deathly Hallows            2007      607           4.9   XXI

Uno podría hacer algo como lo siguiente (se llama _chaining_):

In [24]:
df.loc[df['Año de edición'] <= 2000]['Siglo'] = 'siglo XX'
df

/var/folders/_1/2rv46w25583d0n9gdj9pt4f40000gp/T/ipykernel_96921/1865813456.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc[df['Año de edición'] <= 2000]['Siglo'] = 'siglo XX'

                     Titulo  Año de edición  Páginas  Calificación Siglo
0   The Philosopher's Stone            1997      223           4.5    XX
1    The Chamber of Secrets            1998      251           4.3    XX
2   The Prisoner of Azkaban            1999      317           4.6    XX
3        The Goblet of Fire            2000      636           4.8    XX
4  The Order of the Phoenix            2003      766           4.7   XXI
5     The Half-Blood Prince            2005      607           4.9   XXI
6       The Deathly Hallows            2007      607           4.9   XXI

¿Qué pasó? Por la forma en que `pandas` obtiene los valores pedidos por la máscara `df['Año de edición'] <= 2000`, el proceso de _chaining_ genera un `DataFrame` intermedio que es el que se pretende modificar con `['Siglo']`. El resultado es que `df` no se modifica. 

> Para evitar estos inconvenientes, no se recomienda usar _chaining_ al hacer modificaciones en los `DataFrame`s. 

Para borrar filas o columnas, usamos `.drop`:

In [25]:
df = df.drop(3)
df

                     Titulo  Año de edición  Páginas  Calificación Siglo
0   The Philosopher's Stone            1997      223           4.5    XX
1    The Chamber of Secrets            1998      251           4.3    XX
2   The Prisoner of Azkaban            1999      317           4.6    XX
4  The Order of the Phoenix            2003      766           4.7   XXI
5     The Half-Blood Prince            2005      607           4.9   XXI
6       The Deathly Hallows            2007      607           4.9   XXI

In [29]:
df

                     Titulo  Año de edición  Páginas  Calificación
0   The Philosopher's Stone            1997      223           4.5
1    The Chamber of Secrets            1998      251           4.3
2   The Prisoner of Azkaban            1999      317           4.6
4  The Order of the Phoenix            2003      766           4.7
5     The Half-Blood Prince            2005      607           4.9
6       The Deathly Hallows            2007      607           4.9

In [28]:
df.drop('Siglo',axis=1) # no modifica el dataframe original
display(df)
df.drop('Siglo',axis=1, inplace=True) # modifica el dataframe original 
display(df)

KeyError: "['Siglo'] not found in axis"

Supongamos ahora que tenemos un `DataFrame` (o una serie) con el número de capítulos de los libros:

In [30]:
capitulos_data = {
    "Titulo": [
        "The Philosopher's Stone",
        "The Chamber of Secrets",
        "The Prisoner of Azkaban",
        "The Goblet of Fire",
        "The Order of the Phoenix",
        "The Half-Blood Prince",
        "The Deathly Hallows"
    ],
    "Capítulos": [17, 18, 22, 37, 38, 30, 36]
}

capitulos = pd.DataFrame(capitulos_data)
display(capitulos)

                     Titulo  Capítulos
0   The Philosopher's Stone         17
1    The Chamber of Secrets         18
2   The Prisoner of Azkaban         22
3        The Goblet of Fire         37
4  The Order of the Phoenix         38
5     The Half-Blood Prince         30
6       The Deathly Hallows         36

Quisiéramos agregar los datos de los capítulos a la primer tabla:

In [102]:
df['Capítulos'] = capitulos['Capítulos'] 
display(df)

                     Titulo  Año de edición  Páginas  Calificación  Capítulos
0   The Philosopher's Stone            1997      223           4.5         17
1    The Chamber of Secrets            1998      251           4.3         18
2   The Prisoner of Azkaban            1999      317           4.6         22
4  The Order of the Phoenix            2003      766           4.7         38
5     The Half-Blood Prince            2005      607           4.9         30
6       The Deathly Hallows            2007      607           4.9         36

La columna queda agregada correctamente, y _no_ se agrega el dato en el libro 3 porque ya no está en `df`. Viceversa, si queremos agregar el número de páginas desde `df` a la tabla de `capítulos`:

In [103]:
capitulos['Páginas'] = df['Páginas']
display(capitulos)

                     Titulo  Capítulos  Páginas
0   The Philosopher's Stone         17    223.0
1    The Chamber of Secrets         18    251.0
2   The Prisoner of Azkaban         22    317.0
3        The Goblet of Fire         37      NaN
4  The Order of the Phoenix         38    766.0
5     The Half-Blood Prince         30    607.0
6       The Deathly Hallows         36    607.0

Vemos como naturalmente completa con `Nan` el dato inexistente. Este comportamiento es consistente en todos los casos, ya sea copiando una sola columna o varias, o copiando partes de la tabla utilizando listas o rangos para su definición.

### Operaciones con `DataFrames`

Vamos a ver algunas operaciones de las muchas que se pueden hacer con `DataFrame`s.

> Recordemos que la representación interna de los `DataFrame`s es equivalente a los arreglos de NumPy, con lo cual siempre se podrán realizar cálculos a través de las funciones y métodos que provee dicha biblioteca.

#### Aritméticas

In [31]:
s1 = pd.DataFrame(np.arange(1,11).reshape(5,2), index = ['a', 'b', 'c', 'd', 'e'],columns=['A', 'B'])   
s2 = pd.DataFrame(np.arange(1,11).reshape(2,5).T, index = ['a', 'g', 'h', 'd', 'e'],columns=['A', 'B'])
display(s1,s2)

   A   B
a  1   2
b  3   4
c  5   6
d  7   8
e  9  10

   A   B
a  1   6
g  2   7
h  3   8
d  4   9
e  5  10

In [32]:
1/s1

          A         B
a  1.000000  0.500000
b  0.333333  0.250000
c  0.200000  0.166667
d  0.142857  0.125000
e  0.111111  0.100000

In [33]:
s1 - 42

    A   B
a -41 -40
b -39 -38
c -37 -36
d -35 -34
e -33 -32

Al usar dos o más `DataFrame`s, el proceso de alineamiento de datos de acuerdo a las etiquetas de las filas introduce automáticamente los datos faltantes. Por lo tanto, aquellos valores que faltan no serán, en este caso, sumados y resultarán también en un dato inexistente:

In [107]:
s1+s2

      A     B
a   2.0   8.0
b   NaN   NaN
c   NaN   NaN
d  11.0  17.0
e  14.0  20.0
g   NaN   NaN
h   NaN   NaN

Es posible operar con `DataFrame`s asignando un valor definido a los datos inexistentes, con el argumento `fill_value`:

In [34]:
from IPython.display import display, HTML

def display_side_by_side(dfs:list, captions:list):
    """Display tables side by side to save vertical space
    Input:
        dfs: list of pandas.DataFrame
        captions: list of table captions
    """
    output = ""
    combined = dict(zip(captions, dfs))
    for caption, df in combined.items():
        output += df.style.set_table_attributes("style='display:inline'").set_caption(caption)._repr_html_()
        output += "\xa0\xa0\xa0"
    display(HTML(output))

In [35]:
display_side_by_side([s1,s2],['s1','s2'])

In [110]:
display_side_by_side([s1,s2,s2.add(s1, fill_value=0)],['s1','s2','s2+s1'])

In [36]:
s3 = pd.DataFrame(np.array([1,2]*5).reshape(5,2), index = ['a', 'g', 'h', 'd', 'e'],columns=['A', 'C'])
display(s3)

   A  C
a  1  2
g  1  2
h  1  2
d  1  2
e  1  2

La misma alineación de datos ocurre con las columnas:

In [112]:
s1+s3

      A   B   C
a   2.0 NaN NaN
b   NaN NaN NaN
c   NaN NaN NaN
d   8.0 NaN NaN
e  10.0 NaN NaN
g   NaN NaN NaN
h   NaN NaN NaN

En el caso anterior, la columna B (C) no está en el `DataFrame` s3 (s1), por lo tanto se completan como inexistentes.
Si se utiliza `fill_value`, se completan aquellos datos con `fill_value` que están en alguno de los `DataFrame`s. Si el dato no existe en ninguno de los `DataFrame`s, permanece como inexistente:

In [113]:
display_side_by_side([s1,s3,s3.add(s1, fill_value=0)],['s1','s3','s3+s1'])

In [38]:
print(s3.add(s1, fill_value=0))

      A     B    C
a   2.0   2.0  2.0
b   3.0   4.0  NaN
c   5.0   6.0  NaN
d   8.0   8.0  2.0
e  10.0  10.0  2.0
g   1.0   NaN  2.0
h   1.0   NaN  2.0

In [37]:
s3.mul(s1,fill_value=1) # s3*s1

     A     B    C
a  1.0   2.0  2.0
b  3.0   4.0  NaN
c  5.0   6.0  NaN
d  7.0   8.0  2.0
e  9.0  10.0  2.0
g  1.0   NaN  2.0
h  1.0   NaN  2.0

En resumen, las operaciones realizan una unión entre los `DataFrame`s, y luego, en aquellos casos en que es factible, se ejecuta la operación elemento a elemento.

#### Operaciones entre `DataFrame` y `Series` 

También se pueden hacer operaciones matemáticas entre `DataFrame` y `Series` de manera similar. Sin embargo, hay que aclarar cómo se desarrollan las operaciones dado que mientras `DataFrame` representa una estructura 2D, `Series` es unidimensional. Por defecto, `pandas` propaga la serie por filas, al igual que NumPy. Esta extensión automática de los datos se conoce como _broadcasting_:

In [39]:
arr2D = np.arange(12).reshape(4,3)
arr1D = np.array([3,4,5])
print(arr2D)
print(arr1D)
print(arr2D-arr1D)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[3 4 5]
[[-3 -3 -3]
 [ 0  0  0]
 [ 3  3  3]
 [ 6  6  6]]

In [41]:
df = pd.DataFrame(arr2D, columns = ['A', 'B', 'C'])
v = pd.Series(arr1D, index = ['A', 'B', 'C'])
display(df)
display(v)
df - arr1D  # broadcasting por filas, DataFrame - array 1D

   A   B   C
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

A    3
B    4
C    5
dtype: int64

   A  B  C
0 -3 -3 -3
1  0  0  0
2  3  3  3
3  6  6  6

In [42]:
df - v  # broadcasting por filas, DataFrame - Serie

   A  B  C
0 -3 -3 -3
1  0  0  0
2  3  3  3
3  6  6  6

In [43]:
w = df['A']
df.sub(w, axis='index') # broadcasting por columnas explícito, DataFrame - Serie

   A  B  C
0  0  1  2
1  0  1  2
2  0  1  2
3  0  1  2

In [119]:
df.sub(w, axis=0) # broadcasting por columnas explícito, DataFrame - Serie

   A  B  C
0  0  1  2
1  0  1  2
2  0  1  2
3  0  1  2

In [44]:
df.sub(w, axis=1) # broadcasting por filas explícito, DataFrame - Serie

    A   B   C   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN

En este último caso, dado que los índices de `w` y `df` son todos distintos, se realiza la unión y se completa con `NaN`.

> **ATENCIÓN**: el eje (`axis`) es aquel en el cual se van a emparejar los índices. Así, `axis=0` implica **emparejar** los índices de filas y **propagar**  por columnas. De la misma manera, `axis=1` implica **emparejar** los índices de columnas y **propagar** por filas.

#### Orden 

Para ordenar `DataFrame`s se usa el método `.sort_index()`

In [49]:
df = pd.DataFrame(np.random.rand(4,3), index= ['c','d','a','b'], columns = ['B', 'C', 'A'])
df

          B         C         A
c  0.334610  0.619976  0.176004
d  0.694787  0.897167  0.932700
a  0.983854  0.157381  0.829529
b  0.448250  0.521083  0.467749

In [50]:
df.sort_index() # ordena por los índices de filas

          B         C         A
a  0.983854  0.157381  0.829529
b  0.448250  0.521083  0.467749
c  0.334610  0.619976  0.176004
d  0.694787  0.897167  0.932700

In [51]:
df.sort_index(axis=1) # ordena por los índices de columnas

          A         B         C
c  0.176004  0.334610  0.619976
d  0.932700  0.694787  0.897167
a  0.829529  0.983854  0.157381
b  0.467749  0.448250  0.521083

Pasando el argumento `ascending` (booleano) se puede cambiar el orden por defecto, que corresponde a `ascending=True`. 
Se puede ordenar también de acuerdo a los valores de una (o múltiples) columnas utilizando el método `sort_values`:

In [52]:
df.sort_values('B')

          B         C         A
c  0.334610  0.619976  0.176004
b  0.448250  0.521083  0.467749
d  0.694787  0.897167  0.932700
a  0.983854  0.157381  0.829529

En el caso en que existieran valores faltantes, estos se ordenan al final por defecto, excepto que se pase el argumento opcional `na_position='first'`.

Una operación útil es _ranking_, esto es, asignar un valor desde 1 hasta el número de datos de acuerdo a un orden, desde el valor más bajo al más alto:

In [53]:
s = pd.Series(np.random.rand(5))
s

0    0.142447
1    0.223739
2    0.809740
3    0.834991
4    0.080083
dtype: float64

In [126]:
s.rank()

0    5.0
1    2.0
2    1.0
3    3.0
4    4.0
dtype: float64

#### Estadística 

Es muy común en el análisis de datos tener que calcular valores estadísticos que caracterizan la muestra. `pandas` provee una serie de métodos para realizar estos cálculos.

In [54]:
df = pd.DataFrame(np.random.rand(4,3), index= ['a','b','c','d'], columns = ['A', 'B', 'C'])
df

          A         B         C
a  0.482755  0.136558  0.312016
b  0.242663  0.898340  0.002765
c  0.796619  0.052615  0.633351
d  0.673710  0.510870  0.040348

In [55]:
df.describe()

              A         B         C
count  4.000000  4.000000  4.000000
mean   0.548937  0.399596  0.247120
std    0.241591  0.387605  0.292033
min    0.242663  0.052615  0.002765
25%    0.422732  0.115572  0.030952
50%    0.578232  0.323714  0.176182
75%    0.704437  0.607738  0.392350
max    0.796619  0.898340  0.633351

Cada una de las magnitudes se corresponde a algún parámetro estadístico.

Estas operaciones devuelven un nuevo `DataFrame`. Por ejemplo:

In [56]:
df.sum()

A    2.195747
B    1.598384
C    0.988480
dtype: float64

retorna un `DataFrame` donde los índices corresponden a las etiquetas de cada columna.

> Por defecto, los valores inexistentes (NA, Null, etc.) no son tenidos en cuenta al realizar estas operaciones.

In [57]:
df['A'].sum()

np.float64(2.195747289817598)

### Aplicación de funciones y map

Es posible también aplicar funciones, por ejemplo

In [58]:
df

          A         B         C
a  0.482755  0.136558  0.312016
b  0.242663  0.898340  0.002765
c  0.796619  0.052615  0.633351
d  0.673710  0.510870  0.040348

In [59]:
def f(x):
    return x.max() - x.min()

df.apply(f)

A    0.553956
B    0.845725
C    0.630586
dtype: float64

In [133]:
df.apply(f, axis=1) # por columnas, igual que df.apply(f, axis='columns')

a    0.188404
b    0.378513
c    0.588208
d    0.598722
dtype: float64

In [134]:
df['mean'] = df.mean(axis=1)
df

          A         B         C      mean
a  0.752939  0.917838  0.729434  0.800071
b  0.752812  0.777257  0.398743  0.642937
c  0.383512  0.174772  0.762980  0.440421
d  0.671104  0.447046  0.072382  0.396844

Puede ser necesario aplicar determinada función a todos los valores del `DataFrame`, con `map`:

In [135]:
def round2(x):
    return round(x, 2)


df.map(round2)

      A     B     C  mean
a  0.75  0.92  0.73  0.80
b  0.75  0.78  0.40  0.64
c  0.38  0.17  0.76  0.44
d  0.67  0.45  0.07  0.40